name: Get Epic Stories
on:
  pull_request:
    branches: [ main ]

jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: "https://uneritx.atlassian.net"
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: checkout repo content
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira pandas tabulate
        
    - name: Generate Epic Stories Table
      id: jira_epic_stories
      run: |
        output=$(python jira_epic_stories_table.py)
        echo "${output}}"
        #echo "epic_story_details=$output" >> $GITHUB_OUTPUT
      env:
        JIRA_CLOUD_URL: "https://uneritx.atlassian.net"
        JIRA_USER_LOCAL: ${{ secrets.JIRA_USER }}
        JIRA_TOKEN_LOCAL: ${{ secrets.JIRA_TOKEN }}

    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: ST-1
        comment: "||heading 1||heading 2||heading 3|||col A1|col A2|col A3||col B1|col B2|col B3|"
