name: Get Epic Stories
on:
  pull_request:
    branches: [ main ]
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [ "generate-deployment-ticket" ]

jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: "https://uneritx.atlassian.net"
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: checkout repo content
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira pandas tabulate
        
    - name: Generate Epic Stories Table
      id: jira_epic_stories
      run: |
        output=$(python jira_epic_stories_table.py)
        echo "${output}}"
      env:
        JIRA_CLOUD_URL: "https://uneritx.atlassian.net"
        JIRA_USER_LOCAL: ${{ secrets.JIRA_USER }}
        JIRA_TOKEN_LOCAL: ${{ secrets.JIRA_TOKEN }}

